---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos7.3-vagrant
    box: centos/7
    # centos7.3 image
    # https://app.vagrantup.com/centos/boxes/7
    # https://seven.centos.org/2017/08/updated-centos-vagrant-images-available-v1707-01/
    box_version: "1707.01"
    cpus: 2
    memory: 8192
  - name: centos7.4-vagrant
    box: centos/7
    # centos7.4 image
    # https://app.vagrantup.com/centos/boxes/7
    # https://seven.centos.org/2017/09/updated-centos-vagrant-images-available-v1708-01/
    box_version: "1708.01"
    cpus: 2
    memory: 8192
provisioner:
  name: ansible
  options:
    become: True
  lint:
    name: ansible-lint
    options:
      R: True
      r: "/data/ansible/ansible-lint-custom-rules"
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests
  options:
    verbose: True
  lint:
    name: flake8
